version: "3.8"

services:

  nginx:
    depends_on:
      - backend
    build:
      context: './docker/nginx'
    ports:
      - "8080:80"
    networks:
      - server
    volumes:
      - ./app/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/

  backend:
    depends_on:
      - database
    build:
      context: './docker/php'
    networks:
      - server
      - database
    volumes:
      - ./app/:/var/www/html/
      - ./logs/php:/var/log/
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    deploy:
      mode: replicated
      replicas: 1

  database:
    build:
      context: './docker/postgres'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database

networks:
  server:
    driver: bridge
  database:
    driver: bridge

volumes:
  db-data: