version: "3.8"

services:
  nginx:
    depends_on:
      - backend
    image: laravel_nginx
    ports:
      - "8080:80"
    networks:
      - server
    volumes:
      - ./app/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
  backend:
    depends_on:
      - database
    image: laravel_backend
    networks:
      - server
      - database
      - backend
    volumes:
      - ./app/:/var/www/html/
      - ./logs/php:/var/log/
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: "0.5"
          memory: 1024M
  database:
    image: laravel_database
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - database

networks:
  server:
    driver: bridge
  database:
    name: database_network
    driver: bridge
  backend:
    name: backend_network
    driver: bridge

volumes:
  db-data:
